- name: install and start nginx
  hosts: node
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present


  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: yes



