- name: looping
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Print names in loop
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop:
    - Ramesh
    - Kiran
    - Fani

- name: install packages in loop
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages in loop
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
    - nginx
    - mysql
    - zip
